### ISSUE TITLE
`@class` directive multiline formatting

### ISSUE THREAD

**Issue by zepfietje** [Stillat/blade-parser-typescript#10]
## Unformatted

```blade
@class([
    'foo' => true
])
```

## Formatted

```blade
@class([     'foo' => true, ])
```

## Expected

```blade
@class([
    'foo' => true
])
```

or

```blade
@class(['foo' => true])
```

**Comment by JohnathonKoster** [comment]
Thanks for the report! This behavior has been improved in `1.1.0` and will no longer blindly remove newlines from the internal formatting results (PHP formatting is handled internally using prettier), and will produce the desired output (exact output depends on your prettier configuration).

However, if you would like it to ignore formatting directive parameters entirely you may create a `.blade.format.json` file at the root of your project with the following contents:

```json
{
    "formatDirectivePhpParameters": false
}
```
