### ISSUE TITLE
Conflict with prettier-plugin-tailwindcss

### ISSUE THREAD

**Issue by bnzo** [Stillat/blade-parser-typescript#105]
Since the recent release of [prettier-plugin-blade](https://github.com/tailwindlabs/prettier-plugin-tailwindcss) there is a conflict with `prettier-plugin-blade`

Original issue here: https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/282

**Comment by JohnathonKoster** [comment]
Thanks for the report! I've released `2.1.16` that adds `x-mask` to an internal list to prevent it from being formatted by a feature that attempts to format certain strings as HTML class lists.

This feature can be entirely disabled by adding the following to a `.blade.format.json` file:

```json
{
    "classStrings": {
        "enabled": false
    }
}
```

More information about that feature and configuration can be found here: https://stillat.com/blade-parser/v1/formatting-configuration#content-class-string-emulation

I'll continue to think about excluding other attributes, but will close this for now. If you find additional items just let me know!

**Comment by bnzo** [comment]
Thanks for the quick update @JohnathonKoster, package updated and x-mask is ignored 👍
I do not see any other directives for now, I will let you know if I found some.
