### ISSUE TITLE
Unpaired condition control structure @section

### ISSUE THREAD

**Issue by lucadegasperi** [Stillat/blade-parser-typescript#113]
Hello,

I'm writing this issue to report that the section control structure with a second argument
```php
@section('section-name', 'section-value')
```
should be considered as a self closing control structure and thus be valid instead I'm getting a `Unpaired condition control structure` error.

**Comment by JohnathonKoster** [comment]
Ah, good catch. I'll look into this sometime this week and get an update rolled out

**Comment by lucadegasperi** [comment]
Thank you!

**Comment by JohnathonKoster** [comment]
Do you have the rest of the template that was used to trigger the error? Trying to reproduce with simple templates on my end.

Thanks!

**Comment by lucadegasperi** [comment]
I believe the error might have been triggered by something else inside the file, because I no longer get the error right now after fixing other issues inside the file.

**Comment by JohnathonKoster** [comment]
Sounds good. If you are able to reproduce the error in a valid template (unclosed conditions and condition-likes will throw that error by design), feel free to reopen this issue. I'm going to close it for now, however
