### ISSUE TITLE
`@php` content inside `@if` removed

### ISSUE THREAD

**Issue by zepfietje** [Stillat/blade-parser-typescript#15]
Input:

```blade
@if ('foo')
    @php
        $foo = 'foo';
    @endphp
@endif

```

Output:

```blade
@if ('foo')
    @php
    @endphp
@endif

```

Expected input to remain unchanged.

Also happens for same content inside `@elseif`.
Found it doesn't happen when simply `true` or `false` is passed as the condition.

**Comment by JohnathonKoster** [comment]
This behavior has been improved in `1.1.2` 🙂

**Comment by zepfietje** [comment]
Thanks!
