### ISSUE TITLE
Unpaired condition control structure (bladeParser BLADE_002)

### ISSUE THREAD

**Issue by BrayanCaro** [Stillat/blade-parser-typescript#2]
The following file shows an error:

    |6 col 2-3 error| [bladeParser BLADE_002] Unpaired condition control structure [E]

```blade
{{-- foo.blade.php --}}
@props(['model'])

@can('update', $model)
    update
@else
    any
@endcan
```

But I think that is a valid blade syntax.

The first mention of this issue: https://github.com/yaegassy/coc-blade/issues/15

**Comment by JohnathonKoster** [comment]
Thanks for the report! Will look into this and hope to have an update relatively soon 🙏

**Comment by JohnathonKoster** [comment]
@BrayanCaro 

This has been resolved, with test coverage, in `prettier-plugin-blade@0.1.3` 🙂

**Comment by JohnathonKoster** [comment]
@yaegassy Whoops! Forgot to update that one, `0.1.1` should now be available :)

**Comment by yaegassy** [comment]
@JohnathonKoster Thanks! 🙇
