### ISSUE TITLE
Empty array in `@props` doesn't stay on single line

### ISSUE THREAD

**Issue by zepfietje** [Stillat/blade-parser-typescript#23]
Input
```blade
@props([
    'actions' => [],
    'url',
])
```

Output
```blade
@props([
    'actions' => [
    ],
    'url',
])
```

Expected input to remain unchanged.
Tested with another snippet that doesn't produce this result (so work just fine):

```blade
@props([
    'actions' => [],
    'foo' => [],
])
```

Only appears to happen when there's props without default value.

**Comment by JohnathonKoster** [comment]
Improved in `1.1.6` (and ensured that all previous bug fixes remain). Solved by just removing the alignment logic entirely, and handling the empty arrays specifically inside the internal array formatter (it will choose to use that or prettier based on some internal checks)
