### ISSUE TITLE
Element content formatting issue

### ISSUE THREAD

**Issue by zepfietje** [Stillat/blade-parser-typescript#25]
Input
```blade
<span>
    {{ 'foo' }}:
</span>
```

Output
```blade
<span>
    {{ 'foo' }}
    :
</span>
```

I would expect the input to remain unchanged or be formatted similar to how the following without `{{ }}` would:

Input
```blade
<span>
    foo:
</span>
```

Output
```blade
<span>foo:</span>
```

**Comment by JohnathonKoster** [comment]
Due to the implementation - I'm unlikely to change this at the moment (otherwise it breaks a lot of other things)

**Comment by danharrin** [comment]
The problem is, its does actually affect the output visually. The browser will parse the colon separately to the text, which creates a gap between them

**Comment by JohnathonKoster** [comment]
Will figure something out 🙂 Its an edge case that breaks for the most part (an annoying one, but I think I can get it sorted)

**Comment by JohnathonKoster** [comment]
I've updated the inline echo analyzer, and it will now inline them as text when they are surrounded by content. This will let them be treated as text by prettier, but reversed back into the correct Blade echo once transformation is complete.

With the default settings I use for testing, the following input:

```blade
<span>
    {{ 'foo' }}:
</span>
```

becomes:

```blade
<span>{{ "foo" }}:</span>
```

and the echo and its adjacent content are no longer separated.

However, if the echo does not neighbor any meaningful content in either direction (with respect to any child documents), the transformer will force them to be blocks internally to allow for the following:

```blade

@if ('foo')
        {{ $actions }}
        @elseif ('bar')
        @endif
```

to become:

```blade
@if ("foo")
    {{ $actions }}
@elseif ("bar")
@endif
```

**Comment by danharrin** [comment]
Thank you for your responsivity John!
