### ISSUE TITLE
Weird formatting when merging $attributes

### ISSUE THREAD

**Issue by jasonlbeggs** [Stillat/blade-parser-typescript#3]
This formatted works great for the most part. Thanks for you work!

I noticed one issue when trying it out. When formatting a Blade component where {{ $attributes->merge() }} is used, it adds some weird spacing around the array items. Take the following example:

```blade
<a
    href="#"
    target="_blank"
    {{ $attributes->merge([     'class' =>         'rounded transition focus-visible:outline-none focus-visible:ring focus-visible:ring-red-600', ]) }}
>
    Some link
</a>
```

**Comment by JohnathonKoster** [comment]
Thanks for the report!

I'll have a look and get a fix out as soon as I can! 🙂

**Comment by jasonlbeggs** [comment]
Thanks! Looking forward to using this on all my project 😄

**Comment by JohnathonKoster** [comment]
Note to self: related to Prettier's printWidth configuration option

**Comment by JohnathonKoster** [comment]
Improved in `0.1.5`

**Comment by yaegassy** [comment]
@JohnathonKoster Can you also publish `v1.1.3` of `stillat-blade-parser` to npm?

**Comment by JohnathonKoster** [comment]
> @JohnathonKoster Can you also publish `v1.1.3` of `stillat-blade-parser` to npm?

Should be available soon - I need to look into automating that since I always forget something. Thanks for the reminder 🙌
