### ISSUE TITLE
`@guest` with `@else` and Blade component

### ISSUE THREAD

**Issue by zepfietje** [Stillat/blade-parser-typescript#37]
Same for `@if`.

```blade
@guest
    <x-foo></x-foo>
@else
    <x-foo></x-foo>
@endguest
```

```blade
@guest
        <x-foo></x-foo>
@else
        <x-foo></x-foo>
@endguest
```

Doesn't happen when using `div` instead of `x-foo`.

**Comment by JohnathonKoster** [comment]
Should be in `1.1.15`  🙂

**Comment by JohnathonKoster** [comment]
Also super curious how things have been in general with this latest release (1.1.17 -- did a few updates since the last comment) 🤞🤞
