### ISSUE TITLE
Multiple echoes on single line

### ISSUE THREAD

**Issue by zepfietje** [Stillat/blade-parser-typescript#42]
```blade
Input
<div>
    {{ $foo }}{{ $bar }}
</div>
```

Output
```blade
<div>
    {{ $foo }}
    {{ $bar }}
</div>

```

The echo statements are put on multiple lines, leading to actual issues in the HTML since whitespace is added when they're not right next to each other.
Would expect the input to remain unchanged after formatting in this case.

**Comment by JohnathonKoster** [comment]
Behavior improved in `1.2.1` 🙂
