### ISSUE TITLE
Indentation issue

### ISSUE THREAD

**Issue by zepfietje** [Stillat/blade-parser-typescript#50]
Filament 2.x
`packages/forms/resources/views/components/actions/action.blade.php`

Lines after `$wireClickAction` inside `@php` get indented wrongly.

**Comment by JohnathonKoster** [comment]
Pint will now receive the original internal content and whitespace as of `1.4.6` for formatting inside PHP regions. Having the first line outdented too much will cause inconsistent results. Test suite adjusted to account for this 👍

**Comment by zepfietje** [comment]
Nice, fixed indeed.
