### ISSUE TITLE
`match` indentation

### ISSUE THREAD

**Issue by zepfietje** [Stillat/blade-parser-typescript#54]
Ran into this issue (regression?) on the latest version (1.5.0).

Input and expected output:

```blade
<div
    {{
        $attributes->class([
            'foo',
            match ($foo) {
                'foo' => 'foo',
                'bar' => 'foo',
            },
        ])
    }}
></div>
```

Actual output:

```blade
<div
    {{
        $attributes->class([
            'foo',
            match ($foo) {
            'foo' => 'foo',
            'bar' => 'foo',
            },
        ])
    }}
></div>
```

**Comment by JohnathonKoster** [comment]
I'm not able to reproduce with the provided example (and took a look at the test suite and those existing ones are still passing). Would you be able to share more of the template, and the various formatting configurations that caused it?

Thanks!

**Comment by zepfietje** [comment]
Seems to have been a caching issue...
Only still happened via the VS Code Prettier plugin, but restarting didn't solve it.
Deleted `node_modules` and reinstalled, now it's working fine.

Sorry!
