### ISSUE TITLE
@php directive issues

### ISSUE THREAD

**Issue by agentphoenix** [Stillat/blade-parser-typescript#56]
```blade
@php
    $size = match ($size) {
        'xs' => 'h-5 w-5 md:h-4 md:w-4',
        'sm' => 'h-6 w-6 md:h-5 md:w-5',
        'md' => 'h-7 w-7 md:h-6 md:w-6',
        'lg' => 'h-8 w-8 md:h-7 md:w-7',
        'xl' => 'h-9 w-9 md:h-8 md:w-8',
        default => $size,
    };
@endphp
```

I have Pint setup to add the `declare_strict_types` when it runs. When formatting Blade files with the plugin though, any `@php` tags get formatted with the strict types declaration.

```blade
@php
    declare(strict_types=1);

    $size = match ($size) {
        'xs' => 'h-5 w-5 md:h-4 md:w-4',
        'sm' => 'h-6 w-6 md:h-5 md:w-5',
        'md' => 'h-7 w-7 md:h-6 md:w-6',
        'lg' => 'h-8 w-8 md:h-7 md:w-7',
        'xl' => 'h-9 w-9 md:h-8 md:w-8',
        default => $size,
    };
@endphp
```

PHP throws an error because the declaration isn't on the first line of the file. I moved on to trying to add `@php` to the `ignoreDirectives` in my `.blade.format.json`.

```blade
@php $size = match ($size) { 'xs' => 'h-5 w-5 md:h-4 md:w-4', 'sm' => 'h-6 w-6 md:h-5 md:w-5', 'md' => 'h-7 w-7 md:h-6 md:w-6', 'lg' => 'h-8 w-8 md:h-7 md:w-7', 'xl' => 'h-9 w-9 md:h-8 md:w-8', default => $size, }; @endphp
```

Pushing everything onto a single line sort of defeats the purpose. After that, I noticed the `formatDirectivePhpParameters` and gave that a try.

```blade
<BghhB>
@endphp
```

Maybe I'm just missing something obvious, but how would I tell the plugin to ignore that particular rule in Blade `@php` directives?

**Comment by JohnathonKoster** [comment]
Both issues have been resolved in 1.5.4, with improved test coverage.

Setting `formatDirectivePhpParameters` to `false` will now correctly restore the directive's content.

Additionally, the `declare_strict_types` configuration item will automatically be set to `false` when processing PHP content within Blade templates. You **do not need to do anything** with your configuration for this change to take effect (the Blade formatter will create a copy of your config with its overridden changes inside its temporary working directory).
