### ISSUE TITLE
Blade component attribute comment

### ISSUE THREAD

**Issue by zepfietje** [Stillat/blade-parser-typescript#57]
The following input:
```blade
<x-foo {{-- foo="" --}} />
```

gets formatted as:

```blade
<x-foo {{ -- foo="" -- }} />
```

This only happens on Blade components, not when `x-foo` is replaced by `input` for example.

**Comment by JohnathonKoster** [comment]
Resolved in 1.5.5 🙂

**Comment by zepfietje** [comment]
Perfect, thanks again John!
