### ISSUE TITLE
@click.prevent gets split

### ISSUE THREAD

**Issue by satoved** [Stillat/blade-parser-typescript#58]
Hello,

Wow, the plugin works great! Thanks for a great work.

I only found one issue with AlpineJS usage. I have a tag that actually comes with Laravel Jetstream:

```
<x-jet-dropdown-link
    href="{{ route('logout') }}"
    @click.prevent="$root.submit();"
>
    {{ __('Log Out') }}
</x-jet-dropdown-link>
```

After formatting:

```
<x-jet-dropdown-link
    href="{{ route('logout') }}"
    @click
    .prevent="$root.submit();"
>
    {{ __('Log Out') }}
</x-jet-dropdown-link>
```

The line between @click and .prevent creates a bug in the way tags get parsed by the browser:

<img width="444" alt="image" src="https://github.com/Stillat/blade-parser-typescript/assets/14319239/3bf77746-9d19-4361-ac94-abd7cf08164b">

I guess this formation should somehow be protected from splitting.

Thank you.

**Comment by JohnathonKoster** [comment]
Thanks for the report and fantastic reproduction details! This has been resolved w/. test coverage in 1.5.6 🙌
