### ISSUE TITLE
`@foreach` directive spacing

### ISSUE THREAD

**Issue by zepfietje** [Stillat/blade-parser-typescript#6]
As per usage in Laravel docs: https://laravel.com/docs/10.x/blade#loops.

## Before formatting

```blade
@foreach ([] as $foo)
    
@endforeach
```

## Currently after formatting

```blade
@foreach([] as $foo)
    
@endforeach
```

## Expected after formatting

```blade
@foreach ([] as $foo)
    
@endforeach
```

**Comment by JohnathonKoster** [comment]
Thanks for the report!

I've added a new internal classification for directives to help control the spacing. The following directives will now default to having 1 space after the directive name when formatting (the remaining defaults to 0 spaces):

* foreach
* for
* if
* elseif
* unless

If you'd like to change the spacing from the defaults, you may create a `.blade.format.json` file at the root of your project with the following settings:

```json
{
    "spacesAfterDirective": 0,
    "spacesAfterControlDirective": 1
}
```

The `spacesAfterControlDirective` controls the number of spaces appearing after the directives in the list above, and `spacesAfterDirective` controls all other directives.

**Comment by zepfietje** [comment]
Perfect! I've added some missing directives: https://github.com/Stillat/blade-parser-typescript/pull/11.
