### ISSUE TITLE
@if inside class 

### ISSUE THREAD

**Issue by 1stevengrant** [Stillat/blade-parser-typescript#61]
I have this conditional

```
<div class="@if($step === 1 || $step === 2 || $step === 3 ) bg-white @endif h-3 rounded-full border border-white"></div>
```

when I run the formatter over the top, it becomes

```
<div
        class="@if($step === 1 || $step === 2 || $step === 3 ) bg-white
    @endifh-3 rounded-full border border-white"
    ></div>
```

concatenating the `h-3` class with the @endif statement and breaks the view

**Comment by JohnathonKoster** [comment]
Thanks for the report!

This has been resolved in `1.6.2` (while preserving the existing smart-spacing logic), with additional test coverage.
