### ISSUE TITLE
Use short syntax for named slots

### ISSUE THREAD

**Issue by pascalbaljet** [Stillat/blade-parser-typescript#65]
Can the prettier plugin be configured to use the short slot syntax (with the colon)?

```blade
<x-slot:title>
    {{ __('My Title') }}
</x-slot>

{{-- gets formatted into: --}}

<x-slot name="title">
    {{ __('My Title') }}
</x-slot>
```

**Comment by JohnathonKoster** [comment]
This behavior has been improved in `1.6.5`. Instead of having a new configuration option, the internal parsers will detect which style the slot was originally and restore that after formatting (internally it normalizes it to a normal tag pair so prettier doesn't freak out).

**Comment by pascalbaljet** [comment]
Thanks! Works perfectly!
