### ISSUE TITLE
Concatenation operator spacing no longer respected

### ISSUE THREAD

**Issue by zepfietje** [Stillat/blade-parser-typescript#66]
After updating the formatter from 1.5.6 to 1.6.5 (don't know which exact version caused it), the spacing around the string concatenation operator no longer respects the Pint config. Default Laravel installation with the Blade formatter configured to use Pint should give you this:

```blade
{{ $foo.$bar }}
```

Instead, currently it gives:

```blade
{{ $foo . $bar }}
```

**Comment by JohnathonKoster** [comment]
I see where that happened - will get that updated for you sometime today 🙂

**Comment by zepfietje** [comment]
Glad you found it!

**Comment by JohnathonKoster** [comment]
Resolved as of `1.6.6` 🙌

**Comment by zepfietje** [comment]
Confirmed, thanks!
