### ISSUE TITLE
Does the plugin format indentation?

### ISSUE THREAD

**Issue by ralphjsmit** [Stillat/blade-parser-typescript#72]
I noticed that I am still getting indentation issues that are not being fixed by the plugin. I already updated the ` "useTabs": true,` in the `.prettierc`. 

Thereby a question, does the plugin format indentation, like tabs/spaces?

I do not necessarily care about whatever version the plugin chooses, as long as it always corrects it to one version. 

Thanks!

<img width="1241" alt="Indentation" src="https://github.com/Stillat/blade-parser-typescript/assets/59207045/4bc0793b-c1f8-4193-a8e3-b84b240ae80b">

**Comment by JohnathonKoster** [comment]
Would you be able to provide the text version of the template that is exhibiting the issue? Sometimes its the surrounding context that does weird things, and it really helps to resolve the issues quickly :)

**Comment by ralphjsmit** [comment]
Of course!

For example, this file:

```blade
@php
    use Illuminate\Support\Collection;
@endphp

@props([
    'breadcrumbs',
])

<div {{ $attributes->class(['filament-breadcrumbs flex-1']) }}>
    <ul
        @class([
            'hidden items-center gap-4 text-sm font-medium lg:flex',
            'dark:text-white' => config('filament.dark_mode'),
        ])
    >
        @foreach ($breadcrumbs as $action => $label)
            <li>
                <button
                    type="button"
                    wire:click="{{ $action }}"
                    @class([
                        'text-gray-500' => $loop->last && (! $loop->first),
                        'dark:text-gray-300' => ((! $loop->last) || $loop->first) && config('filament.dark_mode'),
                        'dark:text-gray-400' => $loop->last && (! $loop->first) && config('filament.dark_mode'),
                    ])
                >
                    {{ $label }}
                </button>
            </li>
            
            @if (! $loop->last)
                <li
                    @class([
                        'h-6 -skew-x-12 border-r border-gray-300',
                        'dark:border-gray-500' => config('filament.dark_mode'),
                    ])
                ></li>
            @endif
        @endforeach
    </ul>
</div>
```

<img width="1288" alt="Scherm­afbeelding 2023-07-08 om 18 54 50" src="https://github.com/Stillat/blade-parser-typescript/assets/59207045/30383737-739c-4a1d-ae75-16fe0d554311">

**Comment by ralphjsmit** [comment]
I already ran the formatter earlier on the complete project. Then, PhpStorm updated the indentation (which I don't care about, because the code style fixer should fix it anyway before PR merge). So I ran the formatter again and the indentation change stayed visible. I would have expected the indentation change to be reverted to how the code originally was in the previous commit.

**Comment by JohnathonKoster** [comment]
Thanks for the extra information!

I'm having trouble getting it to reapply the indentation (the formatter should be removing extraneous whitespace) - will keep trying to figure out how to get it to happen, though.

The formatter was intended to be used with spaces instead of tabs, I wonder if that's contributing 🤔

**Comment by ralphjsmit** [comment]
Hey! I tried updating `useTabs: false` and that didn't work either. It seems to just not do anything.

It's a private repo, but I can give you temporary access. Would that be helpful? 

Thanks!

**Comment by JohnathonKoster** [comment]
> Hey! I tried updating `useTabs: false` and that didn't work either. It seems to just not do anything.
> 
> It's a private repo, but I can give you temporary access. Would that be helpful?
> 
> Thanks!

That might help, for sure!

**Comment by ralphjsmit** [comment]
@JohnathonKoster I've just sent you an invite to the repo! Ideally I would like to have the formatter fix the indentation and force one consistent indentation, even though the indentation changed by PhpStorm. E.g. changing indentation by PhpStorm in Blade files is an issue we also have on another big project with multiple devs, because that blows up PRs 😬😄

**Comment by JohnathonKoster** [comment]
Sounds great; thank you! I'll poke around this weekend and see if I can track down what's happening :)

**Comment by howdu** [comment]
Not sure if this is related but after switching from `@shufo/prettier-plugin-blade` I'm finding the @class directive is not getting indented correctly.

The deeper the nesting the more the the indention is getting excessively indented.

E.g
```blade
<div>
    <div>
        <div>
            <div>
                <div
                    @class([
                        'grid',
                        'gap-2' => $key === 'secondary',
                        'gap-4' => $key !== 'secondary'
                    ])
                >
                    <div>Test</div>
                </div>
            </div>
        </div>
    </div>
</div>
```

<img width="978" alt="Screenshot 2023-08-04 at 11 40 32" src="https://github.com/Stillat/blade-parser-typescript/assets/533658/eb78b351-531a-42bf-8c89-08be3e289dfc">

<img width="2042" alt="Screenshot 2023-08-04 at 11 43 15" src="https://github.com/Stillat/blade-parser-typescript/assets/533658/7ce5c3c1-7667-4a0c-87eb-43dc9865ced2">

**Comment by marynazinchenk** [comment]
> Not sure if this is related but after switching from `@shufo/prettier-plugin-blade` I'm finding the @Class directive is not getting indented correctly.
> 
> The deeper the nesting the more the the indention is getting excessively indented.
> 
> E.g
> 
> ```
> <div>
>     <div>
>         <div>
>             <div>
>                 <div
>                     @class([
>                         'grid',
>                         'gap-2' => $key === 'secondary',
>                         'gap-4' => $key !== 'secondary'
>                     ])
>                 >
>                     <div>Test</div>
>                 </div>
>             </div>
>         </div>
>     </div>
> </div>
> ```
> 
> <img alt="Screenshot 2023-08-04 at 11 40 32" width="978" src="https://private-user-images.githubusercontent.com/533658/258397509-eb78b351-531a-42bf-8c89-08be3e289dfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMTU1NzksIm5iZiI6MTcwNjExNTI3OSwicGF0aCI6Ii81MzM2NTgvMjU4Mzk3NTA5LWViNzhiMzUxLTUzMWEtNDJiZi04Yzg5LTA4YmUzZTI4OWRmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQxNjU0MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzZmZGM1NTA2ZjU2YThlZjRmZDY0YWI5ZjU1OGU5NDc5OTA1YjMwMGFhNWFkNTBkNDJhMWUzMjIzNTRkMDI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.92s5DwX5SxJjM-zAOc0C87ey3Tk4XlbdiaVYfeT4Rvg"> <img alt="Screenshot 2023-08-04 at 11 43 15" width="2000" src="https://private-user-images.githubusercontent.com/533658/258398055-7ce5c3c1-7667-4a0c-87eb-43dc9865ced2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMTU1NzksIm5iZiI6MTcwNjExNTI3OSwicGF0aCI6Ii81MzM2NTgvMjU4Mzk4MDU1LTdjZTVjM2MxLTc2NjctNGEwYy04N2ViLTQzZGM5ODY1Y2VkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQxNjU0MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDNjYTJiNTVjM2QyNzJjMTg3NDQxMzJhZTc1ODZlOTIwM2Q4ZDAyNjUwOGYyYTUzNjU3NGMyNTVkNTJhZDFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iMcPIvwKOCDfcFZk8sEsPnpHHyQVzJ6oBMYje7JH7t0">

same problem with @include directive

**Comment by JohnathonKoster** [comment]
@marynazinchenk Would you be able to provide your prettier settings, blade formatter settings (if configured), version numbers, as well as the original document _as an attachment_?

I've yet to reproduce this on my end. Thanks!
