### ISSUE TITLE
Wrong indentation

### ISSUE THREAD

**Issue by zepfietje** [Stillat/blade-parser-typescript#73]
https://github.com/filamentphp/filament/blob/3.x/packages/notifications/resources/views/notification.blade.php

```blade
<x-filament-notifications::notification
    :notification="$notification"
    :x-transition:enter-start="
        \Illuminate\Support\Arr::toCssClasses([
            'opacity-0',
            ($this instanceof \Filament\Notifications\Http\Livewire\Notifications)
            ? match (static::$horizontalAlignment) {
                'left' => '-translate-x-12',
                'right' => 'translate-x-12',
                'center' => match (static::$verticalAlignment) {
                    'top' => '-translate-y-12',
                    'bottom' => 'translate-y-12',
                    'center' => null,
                },
            }
            : null,
        ])
    "
    ...
```

The ternary expression arms are missing one level of indentation.

**Comment by JohnathonKoster** [comment]
Just want to make sure I'm on the same page, are you referring to this content here 🙂?

```php
            ? match (static::$horizontalAlignment) {
                'left' => '-translate-x-12',
                'right' => 'translate-x-12',
                'center' => match (static::$verticalAlignment) {
                    'top' => '-translate-y-12',
                    'bottom' => 'translate-y-12',
                    'center' => null,
                },
            }
            : null,
```

**Comment by zepfietje** [comment]
Yes! As you can see, the `?` and `:` are on the same level as the `(` the line above it.

**Comment by JohnathonKoster** [comment]
Tracked it down. Pint/cs-fixer will *not* add that indentation by itself. I've refactored some code that normalizes the left whitespace when formatting directive parameters to help Pint preserve that whitespace.

The ternary arms will not automatically be indented by Pint, but if you re-indent them, that relative indentation will now be preserved inside Blade component params. as of `1.6.10` 👍

**Comment by zepfietje** [comment]
Yeah it's mainly about making sure it's preserved if you put them on the correct level manually. Thanks, John!
