### ISSUE TITLE
Validator issue with email

### ISSUE THREAD

**Issue by driftingly** [Stillat/blade-parser-typescript#75]
I ran into a `SyntaxError: Unpaired condition control structure` issue while using the prettier plugin:

```blade
@if (true)
    test@example.com
@endif
```

```
resources/views/test.blade.php
[error] resources/views/test.blade.php: SyntaxError: Unpaired condition control structure
[error] 
[error]  >1| @if (true)
[error]   2|     test@example.com
[error]   3| @endif
[error]   4| 
[error] 
[error]     at Fa.preFormatter (/Users/anthony/Sites/testing/node_modules/prettier-plugin-blade/plugin.js:239:2118)
[error]     at Fa.formatDocument (/Users/anthony/Sites/testing/node_modules/prettier-plugin-blade/plugin.js:239:1002)
[error]     at Object.print (/Users/anthony/Sites/testing/node_modules/prettier-plugin-blade/plugin.js:250:5461)
[error]     at callPluginPrintFunction (/Users/anthony/Sites/testing/node_modules/prettier/index.js:8601:26)
[error]     at mainPrintInternal (/Users/anthony/Sites/testing/node_modules/prettier/index.js:8550:22)
[error]     at mainPrint (/Users/anthony/Sites/testing/node_modules/prettier/index.js:8537:18)
[error]     at printAstToDoc (/Users/anthony/Sites/testing/node_modules/prettier/index.js:8529:18)
[error]     at coreFormat (/Users/anthony/Sites/testing/node_modules/prettier/index.js:8837:20)
[error]     at formatWithCursor2 (/Users/anthony/Sites/testing/node_modules/prettier/index.js:9021:18)
[error]     at Object.formatWithCursor (/Users/anthony/Sites/testing/node_modules/prettier/index.js:38183:12)
```

I couldn't get many variations to work, but for some reason, this works:

```blade
@if (true)
    @foreach (["test@example.com"] as $email)
        {{ $email }}
    @endforeach
@endif
```

**Comment by driftingly** [comment]
Thank you for all your hard work 🙌

**Comment by JohnathonKoster** [comment]
Corrected with the `1.6.11` release 🙂

**Comment by yaegassy** [comment]
@JohnathonKoster Hi, The version of the `stillat-blade-parser` package itself, currently published in npm, is version `1.1.11`. Could you update this as well?

**Comment by JohnathonKoster** [comment]
@yaegassy  I've tagged a `1.2.0` release and published it that contains all of the changes since the last update 🙌

**Comment by yaegassy** [comment]
@JohnathonKoster Thank you. I have one point of concern. The size of the package seems to be very large, is that a problem?

- v1.1.11
  - Unpacked Size: `2.85 MB`
  - https://www.npmjs.com/package/stillat-blade-parser/v/1.1.11

- v1.2.0
  - Unpacked Size: `25.6 MB`
  - https://www.npmjs.com/package/stillat-blade-parser/v/1.2.0

**Comment by JohnathonKoster** [comment]
there have been quite a few changes since 1.1.11 that have impacted overall size (mainly to resolve formatting issues). I plan to investigate potential ways of splitting the parser and formatters in the future to reduce the bundle 👍

**Comment by yaegassy** [comment]
Thanks for the reply. Once again, thank you for a great parser. I will continue to support you.
