### ISSUE TITLE
[Prettier plugin] Plain text empty forelse statement is missing whitespace

### ISSUE THREAD

**Issue by Roardom** [Stillat/blade-parser-typescript#83]
A file containing a forelse loop with an empty statement where the empty is plain text (if it's wrapped in html tags it works)

```blade
@forelse ($items as $item)
    {{ $item }}
@empty
    No items
@endforelse
```

becomes

```blade
@forelse ($items as $item)
    {{ $item }}
@emptyNo items@endforelse
```

`prettier-plugin-blade`: 1.6.14
`prettier`:  2.8.8

**Comment by JohnathonKoster** [comment]
Improved in `v1.6.15`, with additional test coverage
