### ISSUE TITLE
[Prettier plugin] Unescaped blade inside alpine js x-data

### ISSUE THREAD

**Issue by Roardom** [Stillat/blade-parser-typescript#84]
A file that contains unescaped blade data inside alpine js x-data

```blade
<div x-data="{ data: {!! $data !!} }"></div>
```

becomes

```blade
<div x-data="{ data: {! ! $data ! ! } }"></div>
```

`prettier-plugin-blade`: 1.6.14
`prettier`:  2.8.8

**Comment by JohnathonKoster** [comment]
Improved in `v1.6.15`, with additional test coverage
