### ISSUE TITLE
Array prop on single line

### ISSUE THREAD

**Issue by zepfietje** [Stillat/blade-parser-typescript#9]
## Unformatted

```blade
@props([
    'foo' => [],
])
```

## Formatted

```blade
@props([
    'foo' => [
    ],
    
])
```

## Expected

```blade
@props([
    'foo' => [],
])
```

**Comment by JohnathonKoster** [comment]
Thanks for the report! This is similar to #10, however there are some special considerations internally when formatting `@props`.

With the release of `1.1.0`, if the internal parser detects an associative array at the root of the `@props`, like in your example, it will utilize the same behavior as other directive parameter formatting and produce the expected output (exact output depends on your exact prettier configuration).

However, if the root of `@props` is not an associative array, the internal array formatting will be used instead to accommodate the following `@props` formatting styles:

**Input** 

```blade
@props([
    'heading', 'footer',
    'other',
])
```

**Output**

```blade
@props([
    'heading',
    'footer',
    'other',
])
```

If you would like the formatter to ignore `@props` and other directive parameters when formatting, you may create a `.blade.format.json` file at the root of your project with the following contents:

```json
{
    "formatDirectivePhpParameters": false
}
```

**Comment by zepfietje** [comment]
I'm still getting the exact unexpected output as reported.
Have you tested the example I provided, @JohnathonKoster?

**Comment by JohnathonKoster** [comment]
I have spotted the oversight with the provided sample (issue with double counting both the key/value components of an array as distinct elements).

I've updated this and issued it in patch release 1.1.1 and have added a test case for this scenario:

https://github.com/Stillat/blade-parser-typescript/blob/main/src/test/formatter_props_directive.test.ts#L129-L138

**Comment by zepfietje** [comment]
Thanks!
