### ISSUE TITLE
SyntaxError: Unpaired condition control structure (@hasSection)

### ISSUE THREAD

**Issue by luveqz** [Stillat/blade-parser-typescript#92]
## Problem

I'm trying to use the [@hasSection](https://laravel.com/docs/10.x/blade#section-directives) directive, but then the plugin throws a:

```
SyntaxError: Unpaired condition control structure
```

Code:
```blade
@hasSection('sidebar') 
  <aside class="sidebar">
    @yield('sidebar')
  </aside>
@endif 
```

I tried to make Prettier to [ignore that block](https://stillat.com/blade-parser/v1/formatting-configuration#content-ignoring-parts-of-a-template), but it didn't work either.

## Demo
Open this minimal StackBlitz [demo](https://stackblitz.com/edit/stackblitz-starters-j8uwav?file=.prettierrc) and run:

```
npm run lint app.blade.php
```

**Comment by JohnathonKoster** [comment]
The ignore start/end just stops it from formatting that specific section of the document (but the parser will still attempt to parse it).

I've updated the parser and just published v2.1.1 to address this specific parsing issue, however
